[build]
builder = "NIXPACKS"
BuildCommand = "npm install --legacy-peer-deps"

[deploy]
startCommand = "npm start"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10