[build]
builder = "NIXPACKS"
BuildCommand = "npm ci --legacy-peer-deps"

[deploy]
startCommand = "npm run start"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10